### ISSUE TITLE
回复

### ISSUE THREAD

**Issue by 283006603** [xing16/WanAndroid#6]
我按照你的demo写，有问题啊，大哥能回复一下我嘛

**Comment by xing16** [comment]
> 我按照你的demo写，有问题啊，大哥能回复一下我嘛

什么问题？

**Comment by 283006603** [comment]
就是按照你的组件化的工程看的，我只不过是按照你的没写成组件化的，但是有个问题我搞了很久了，真的希望你能帮我看看，不胜感激。
我已经很久没接触过APP了，我希望通过参照你的例子能重回APP



在ProjectPageFragment这里，我loadData这里的log都打印出来了，准备去加载了，但是奔溃，只要把presenter.getProject(id,page)注释掉（相当于不加载）就不会崩掉，所以切入点都在这里
但是我查了很久，真的没有查出问题，崩溃的日志是

说是类型转化错误，但是我类型根本没错误啊。麻烦大神真的帮我看一下，我不知道问谁了




------------------ 原始邮件 ------------------
发件人: "Star.tao"<notifications@github.com>;
发送时间: 2019年7月9日(星期二) 晚上8:22
收件人: "xing16/WanAndroid"<WanAndroid@noreply.github.com>;
抄送: "Mr.Li"<283006603@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xing16/WanAndroid] 回复 (#6)



 
我按照你的demo写，有问题啊，大哥能回复一下我嘛
  
什么问题？

**Comment by xing16** [comment]
> 就是按照你的组件化的工程看的，我只不过是按照你的没写成组件化的，但是有个问题我搞了很久了，真的希望你能帮我看看，不胜感激。 我已经很久没接触过APP了，我希望通过参照你的例子能重回APP 在ProjectPageFragment这里，我loadData这里的log都打印出来了，准备去加载了，但是奔溃，只要把presenter.getProject(id,page)注释掉（相当于不加载）就不会崩掉，所以切入点都在这里 但是我查了很久，真的没有查出问题，崩溃的日志是 说是类型转化错误，但是我类型根本没错误啊。麻烦大神真的帮我看一下，我不知道问谁了

没看到日志啊，贴下代码

**Comment by 283006603** [comment]
------------------ 原始邮件 ------------------
发件人: "Star.tao"<notifications@github.com>;
发送时间: 2019年7月10日(星期三) 中午11:15
收件人: "xing16/WanAndroid"<WanAndroid@noreply.github.com>;
抄送: "Mr.Li"<283006603@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xing16/WanAndroid] 回复 (#6)



 
就是按照你的组件化的工程看的，我只不过是按照你的没写成组件化的，但是有个问题我搞了很久了，真的希望你能帮我看看，不胜感激。 我已经很久没接触过APP了，我希望通过参照你的例子能重回APP 在ProjectPageFragment这里，我loadData这里的log都打印出来了，准备去加载了，但是奔溃，只要把presenter.getProject(id,page)注释掉（相当于不加载）就不会崩掉，所以切入点都在这里 但是我查了很久，真的没有查出问题，崩溃的日志是 说是类型转化错误，但是我类型根本没错误啊。麻烦大神真的帮我看一下，我不知道问谁了
  
没看到日志啊，贴下代码

**Comment by 283006603** [comment]
这是工程，其实就一个界面




------------------ 原始邮件 ------------------
发件人: "Star.tao"<notifications@github.com>;
发送时间: 2019年7月10日(星期三) 中午11:15
收件人: "xing16/WanAndroid"<WanAndroid@noreply.github.com>;
抄送: "Mr.Li"<283006603@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xing16/WanAndroid] 回复 (#6)



 
就是按照你的组件化的工程看的，我只不过是按照你的没写成组件化的，但是有个问题我搞了很久了，真的希望你能帮我看看，不胜感激。 我已经很久没接触过APP了，我希望通过参照你的例子能重回APP 在ProjectPageFragment这里，我loadData这里的log都打印出来了，准备去加载了，但是奔溃，只要把presenter.getProject(id,page)注释掉（相当于不加载）就不会崩掉，所以切入点都在这里 但是我查了很久，真的没有查出问题，崩溃的日志是 说是类型转化错误，但是我类型根本没错误啊。麻烦大神真的帮我看一下，我不知道问谁了
  
没看到日志啊，贴下代码
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


从QQ邮箱发来的超大附件

TuttiStore.7z (15.86M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=75626334ea55319cbc34bd244563014c03505155570251051a075450014e075252524e0c0657004e030653020607565651065706636e33374216175d30175c11524c544e6327&t=exs_ftn_download&code=7bc4cc3c

**Comment by xing16** [comment]
> 这是工程，其实就一个界面
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Star.tao"<notifications@github.com>; 发送时间: 2019年7月10日(星期三) 中午11:15 收件人: "xing16/WanAndroid"<WanAndroid@noreply.github.com>; 抄送: "Mr.Li"<283006603@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [xing16/WanAndroid] 回复 (#6) 就是按照你的组件化的工程看的，我只不过是按照你的没写成组件化的，但是有个问题我搞了很久了，真的希望你能帮我看看，不胜感激。 我已经很久没接触过APP了，我希望通过参照你的例子能重回APP 在ProjectPageFragment这里，我loadData这里的log都打印出来了，准备去加载了，但是奔溃，只要把presenter.getProject(id,page)注释掉（相当于不加载）就不会崩掉，所以切入点都在这里 但是我查了很久，真的没有查出问题，崩溃的日志是 说是类型转化错误，但是我类型根本没错误啊。麻烦大神真的帮我看一下，我不知道问谁了 没看到日志啊，贴下代码 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. 从QQ邮箱发来的超大附件 TuttiStore.7z (15.86M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=75626334ea55319cbc34bd244563014c03505155570251051a075450014e075252524e0c0657004e030653020607565651065706636e33374216175d30175c11524c544e6327&t=exs_ftn_download&code=7bc4cc3c

你把错误日志也贴下，不然我要导入工程

**Comment by 283006603** [comment]
2019-07-10 11:28:59.400 27528-27528/com.apptutti.tuttistore D/ProjectPagePresenter: aaaa
2019-07-10 11:28:59.698 27528-27528/com.apptutti.tuttistore W/System.err:     at com.apptutti.tuttistore.mvp.presenter.ProjectPagePresenter$1.onSuccess(ProjectPagePresenter.java:18)
2019-07-10 11:28:59.703 27528-27528/com.apptutti.tuttistore E/TAG: <<<<<<<<<<<<<<<----START---->>>>>>>>>>>>>>>>>>
    SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@5c06aa3
    versionCode=1
    BOARD=mt6750
    BOOTLOADER=unknown
    TYPE=user
    ID=NRD90M
    TIME=1553053238000
    BRAND=vivo
    TAG=Build
    HARDWARE=mt6755
    SERIAL=SSD6UCUOY9FEPJIB
    SUPPORTED_ABIS=[Ljava.lang.String;@7d41a0
    CPU_ABI=arm64-v8a
    IS_DEBUGGABLE=false
    RADIO=unknown
    MANUFACTURER=vivo
    IS_EMULATOR=false
    SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@d1059d2
    TAGS=release-keys
    CPU_ABI2=
    UNKNOWN=unknown
    PERMISSIONS_REVIEW_REQUIRED=false
    USER=compiler
    FINGERPRINT=vivo/PD1705/PD1705:7.0/NRD90M/1553053260:user/release-keys
    HOST=compiler033
    versionName=1.0
    PRODUCT=PD1705
    DISPLAY=NRD90M release-keys
    MODEL=vivo Y69A
    DEVICE=PD1705
    io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | com.apptutti.tuttistore.bean.ProjectPageItem cannot be cast to com.apptutti.tuttistore.bean.ProjectResult
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:121)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6327)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1076)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
     Caused by: java.lang.ClassCastException: com.apptutti.tuttistore.bean.ProjectPageItem cannot be cast to com.apptutti.tuttistore.bean.ProjectResult
        at com.apptutti.tuttistore.mvp.presenter.ProjectPagePresenter$1.onSuccess(ProjectPagePresenter.java:18)
        at com.apptutti.tuttistore.base.BaseObserver.onNext(BaseObserver.java:49)
        at com.apptutti.tuttistore.base.BaseObserver.onNext(BaseObserver.java:11)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
        at android.os.Handler.handleCallback(Handler.java:836) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:203) 
        at android.app.ActivityThread.main(ActivityThread.java:6327) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1076) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937) 
    java.lang.ClassCastException: com.apptutti.tuttistore.bean.ProjectPageItem cannot be cast to com.apptutti.tuttistore.bean.ProjectResult
        at com.apptutti.tuttistore.mvp.presenter.ProjectPagePresenter$1.onSuccess(ProjectPagePresenter.java:18)
        at com.apptutti.tuttistore.base.BaseObserver.onNext(BaseObserver.java:49)
        at com.apptutti.tuttistore.base.BaseObserver.onNext(BaseObserver.java:11)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6327)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1076)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
    <<<<<<<<<<<<<<<<<----END---->>>>>>>>>>>>>>>>>>





麻烦大哥了，我想继续跟着你这个项目照着写一遍，求指教。




------------------ 原始邮件 ------------------
发件人: "Star.tao"<notifications@github.com>;
发送时间: 2019年7月10日(星期三) 中午11:32
收件人: "xing16/WanAndroid"<WanAndroid@noreply.github.com>;
抄送: "Mr.Li"<283006603@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xing16/WanAndroid] 回复 (#6)



 
这是工程，其实就一个界面
 …
 ------------------ 原始邮件 ------------------ 发件人: "Star.tao"notifications@github.com; 发送时间: 2019年7月10日(星期三) 中午11:15 收件人: "xing16/WanAndroid"WanAndroid@noreply.github.com; 抄送: "Mr.Li"283006603@qq.com;"Author"author@noreply.github.com; 主题: Re: [xing16/WanAndroid] 回复 (#6) 就是按照你的组件化的工程看的，我只不过是按照你的没写成组件化的，但是有个问题我搞了很久了，真的希望你能帮我看看，不胜感激。 我已经很久没接触过APP了，我希望通过参照你的例子能重回APP 在ProjectPageFragment这里，我loadData这里的log都打印出来了，准备去加载了，但是奔溃，只要把presenter.getProject(id,page)注释掉（相当于不加载）就不会崩掉，所以切入点都在这里 但是我查了很久，真的没有查出问题，崩溃的日志是 说是类型转化错误，但是我类型根本没错误啊。麻烦大神真的帮我看一下，我不知道问谁了 没看到日志啊，贴下代码 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. 从QQ邮箱发来的超大附件 TuttiStore.7z (15.86M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=75626334ea55319cbc34bd244563014c03505155570251051a075450014e075252524e0c0657004e030653020607565651065706636e33374216175d30175c11524c544e6327&t=exs_ftn_download&code=7bc4cc3c
  
你把错误日志也贴下，不然我要导入工程

**Comment by xing16** [comment]
MainApiService 的这个方法 返回值 泛型错了 ，不应该是 ProjectPageItem ,应该是  ProjectResult

@GET("project/list/{page}/json")
    Observable<BaseResponse<ProjectPageItem>> getProjects(@Path("page") int page, @Query("cid") int id);

**Comment by 283006603** [comment]
哥我改了，没什么问题，我能加下你的QQ么？




------------------ 原始邮件 ------------------
发件人: "Star.tao"<notifications@github.com>;
发送时间: 2019年7月10日(星期三) 中午11:39
收件人: "xing16/WanAndroid"<WanAndroid@noreply.github.com>;
抄送: "Mr.Li"<283006603@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xing16/WanAndroid] 回复 (#6)




MainApiService 的这个方法 返回值 泛型错了 ，不应该是 ProjectPageItem ,应该是  ProjectResult
 
@get("project/list/{page}/json")
 Observable<BaseResponse> getProjects(@path("page") int page, @query("cid") int id);

**Comment by xing16** [comment]
> 哥我改了，没什么问题，我能加下你的QQ么？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Star.tao"<notifications@github.com>; 发送时间: 2019年7月10日(星期三) 中午11:39 收件人: "xing16/WanAndroid"<WanAndroid@noreply.github.com>; 抄送: "Mr.Li"<283006603@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [xing16/WanAndroid] 回复 (#6) MainApiService 的这个方法 返回值 泛型错了 ，不应该是 ProjectPageItem ,应该是 ProjectResult @get("project/list/{page}/json") Observable<BaseResponse> getProjects(@path("page") int page, @query("cid") int id); — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

1429161712，手机上基本不用 qq
